@startuml

class PersonajeVideojuego{

    +PersonajeVideojuego()=default
    +PersonajeVideojuego(int x, int y,int vida, int mana, int damageArma)
    +int getposX()
    +int getposY()
    +void movimiento(int x, int y)
    +int getVida()
    +void setVida()
    +int getMana()
    +void setMana()
    +void incrementarVida()
    +void incrementarMana()
    +void ataqueBasico(Enemigo golpeado)
    +void hab1(Enemigo golpeado)
    +void hab2(Enemigo golpeado)
    +void equiparArma(Arma* armaequipada)
    
    -int posX=0
    -int posY=0
    -int vidaAct=100
    -int vidaMax=100
    -int manaAct=50
    -int manaMax=50
    -int vitalidad=12
    -int inteligencia=10
    -int fuerza=12
    -Arma armaEquipada
    -float damageHab1=1,2
    -int consumoHab1=10
    -float damageHab2=1,5
    -int consumoHab2=20
}

class Enemigo{
    +Enemigo()=default
    +Enemigo (int vida, int damageBasico)
    +int getVida()
    +int getDamage()
    +Enemigo& setNombre()
    +string getNombre()

    -string Nombre
    -int vida=40
    -int damageBasico=5
}

class Arma{
    +string getNombre()
    +int getDamage()
    -string nombre
    -int damage
}

@enduml